name: Update Year

on:
  workflow_dispatch:

jobs:
  update-year:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set current year environment variable
      run: echo "CURRENT_YEAR=$(date +'%Y')" >> $GITHUB_ENV

    - name: Update year in index.php
      run: |
        sed -i "s/define('SMF_SOFTWARE_YEAR', '[0-9]\{4\}');/define('SMF_SOFTWARE_YEAR', '${{ env.CURRENT_YEAR }}');/" index.php

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update year to ${{ env.CURRENT_YEAR }}
        branch: 3.0/update-year-${{ env.CURRENT_YEAR }}
        title: Update year to ${{ env.CURRENT_YEAR }}
        body: This commit updates `SMF_SOFTWARE_YEAR` to ${{ env.CURRENT_YEAR }} in `index.php`.
